Fix deploy for templated bundles
Templated bundle deploys currently do not work due to the check
for whether to do local overlay template looking at the wrong
file, resulting in a traceback like this:

    Traceback (most recent call last):
      File "/home/frode/src/opendev.org/x/charm-ovn-chassis/src/.tox/func-target/bin/functest-run-suite", line 8, in <module>
        sys.exit(main())
      File "/home/frode/src/opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.10/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 404, in main
        func_test_runner(
      File "/home/frode/src/opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.10/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 312, in func_test_runner
        run_env_deployment(env_deployment, keep_model=preserve_model,
      File "/home/frode/src/opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.10/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 144, in run_env_deployment
        deploy.deploy(
      File "/home/frode/src/opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.10/site-packages/zaza/charm_lifecycle/deploy.py", line 396, in deploy
        deploy_bundle(bundle, model, model_ctxt=model_ctxt, force=force,
      File "/home/frode/src/opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.10/site-packages/zaza/charm_lifecycle/deploy.py", line 358, in deploy_bundle
        for overlay in render_overlays(bundle, tmpdirname,
      File "/home/frode/src/opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.10/site-packages/zaza/charm_lifecycle/deploy.py", line 305, in render_overlays
        if should_render_local_overlay(bundle):
      File "/home/frode/src/opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.10/site-packages/zaza/charm_lifecycle/deploy.py", line 287, in should_render_local_overlay
        return is_local_overlay_enabled_in_bundle(bundle)
      File "/home/frode/src/opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.10/site-packages/zaza/charm_lifecycle/deploy.py", line 258, in is_local_overlay_enabled_in_bundle
        with open(bundle, 'r') as stream:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/frode/src/opendev.org/x/charm-ovn-chassis/src/tests/bundles/bundle.yaml

This commit fixes that.

Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>