tox: Avoid running setup.py directly
Direct calls to setup.py have been deprecated [0] and
they recently started to cause functional test to fail with
error:

NotImplementedError: Support for egg-based install has been removed.

This change removes explicit setup.py calls from tox commands, as it
shouldn't be necessary to explicitly install local project into the
tox virtual environment anyway.

[0] https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html

Signed-off-by: Martin Kalcok <martin.kalcok@canonical.com>