Pin aiohttp<4.0.0
aiohttp doesn't compile with the gcc available in Ubuntu Jammy, the
error raised is:

aiohttp/_http_parser.c:16227:5: error: lvalue required as increment operand

(cherry picked from commit 9eb432ebf426bdc3435b8512ee414fad2168acd9)